name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 17 needs gradle 7
        java: [8, 11]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: gradle
    - run: |
        ./gradlew clean check --refresh-dependencies
        ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.8.11
        ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.9.10
        ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.10.4
        ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.11.3
        ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.12.3
        ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.14.1
        ./gradlew codeCoverageReport
